### ISSUE TITLE
I have a Problem in Turbo Mode

### ISSUE THREAD

**Issue by ppeyman** [breezefront/module-breeze#28]
Hi 
when I turn turbo off all of pages works well .
i integrated some of modules to breeze theme and  After turn on turbo mode then 
some page who has js integration doesn't works well (when I normaly browse pages)  but when i refresh specifc page works well i don't know why ?! 
i recorded a [video](https://www.veed.io/view/63f4a201-a3c9-450b-b4e9-13607a3b293e/showcase?sharingWidget=true) for it 

Thank You Please help!

**Comment by vovayatsyuk** [comment]
How do you initialize your js component?

**Comment by ppeyman** [comment]
[this](https://github.com/breezefront/theme-frontend-breeze-evolution/issues/11#issuecomment-1266896678) is my js file 
i check the initialize but i don't understand how work with it
