### ISSUE TITLE
how can i remove js file from module who has integreated?

### ISSUE THREAD

**Issue by ppeyman** [breezefront/module-breeze#29]
i integrated 3 module with breeze theme and module.
for example i integreated like below : 
Vendor_breezeSms
Vendor_breezeEmail
integreated js file load well !

but i have a problem bcs load old js file in site how can i remove old js file ?

i Tried ways like requirejs and etc. doesn't work do you have any idea for that ?

**Comment by vovayatsyuk** [comment]
How did you add that old js file? If you've used layout update XML to add the file, then you can remove the file via layout update XML too.

**Comment by ppeyman** [comment]
i added with below code : 
```
<body>
        <referenceBlock name="breeze.js">
  <arguments>
    <argument name="bundles" xsi:type="array">
      <item name="default" xsi:type="array">
        <item name="items" xsi:type="array">
          <item name="Vendor_moduleone/js/jsfile" xsi:type="array">
            <item name="path" xsi:type="string">My_vendor/js/myjs</item>
            <item name="enabled" xsi:type="helper" helper="Swissup\Breeze\Helper\Config::isEnabled">
              <param name="path">venmodule/general/enable</param>
            </item>
          </item>
        </item>
      </item>
    </argument>
  </arguments>
</referenceBlock>
    </body>
```


how to remove **jsfile** ?

**Comment by vovayatsyuk** [comment]
I don't understand. 

I want to know how you added the file that you want to remove.
Do you want to remove this file `<item name="path" xsi:type="string">My_vendor/js/myjs</item>`?

**Comment by ppeyman** [comment]
i created a module with below address: 
```
My / Vendor / etc / Module.xml
My / Vendor / view / frontend / layout / breeze_default.xml ( who added code in above comment )
My / Vendor / view / frontend / web / js / myjs.js (Copy of Vendor_moduleone/js/jsfile )
My / Vendor / registration.php
```
i added **myjs** file with breeze_default.xml.
yes i want to remove `<item name="path" xsi:type="string">My_vendor/js/myjs</item>`

**Comment by vovayatsyuk** [comment]
Can you explain why did you add it if you don't need it?

**Comment by ppeyman** [comment]
if i don't remove it we have a error on console because old js file doesn't compatible with breeze module and etc
Are you saying that I went the wrong way? 
i saw the magfanblog breeze module and want to create something like that 

regard

**Comment by vovayatsyuk** [comment]
This code:

```xml
<item name="Vendor_moduleone/js/jsfile" xsi:type="array">
  <item name="path" xsi:type="string">My_vendor/js/myjs</item>
  <item name="enabled" xsi:type="helper" helper="Swissup\Breeze\Helper\Config::isEnabled">
    <param name="path">venmodule/general/enable</param>
  </item>
</item>
```

is instruction for Breeze module. All js files added with this instruction must be compatible with Breeze.

**Comment by ppeyman** [comment]
> This code:
> 
> ```
> <item name="Vendor_moduleone/js/jsfile" xsi:type="array">
>   <item name="path" xsi:type="string">My_vendor/js/myjs</item>
>   <item name="enabled" xsi:type="helper" helper="Swissup\Breeze\Helper\Config::isEnabled">
>     <param name="path">venmodule/general/enable</param>
>   </item>
> </item>
> ```
> 
> is instruction for Breeze module. All js files added with this instruction must be compatible with Breeze.

Yes, it means when we use this code
What happens to the previous file?

**Comment by vovayatsyuk** [comment]
Sorry, but I don't understand what are you saying (what previous file? Breeze doesn't add any js files on its own. Everything is controlled by the developer). Please share your code somewhere so I can see it.

**Comment by ppeyman** [comment]
> Sorry, but I don't understand what are you saying (what previous file? Breeze doesn't add any js files on its own. Everything is controlled by the developer). Please share your code somewhere so I can see it.


for example [this](https://github.com/breezefront/theme-frontend-breeze-evolution/issues/11#issuecomment-1266896678) file is for a module and doesn't compatible with breeze rules
i compatibled it with overwriting but this way doesn't well because i don't want change the source or core of the module.
so i need create a module to compatible it with breeze for example  somthing like [module-front-breeze-magfan](https://github.com/breezefront/module-breeze-magefan-blog) 
now i have created a module to integrated it everything is works well but source or main js  file who doesn't compatible with breeze is loaded
and we have error from console 
all of my question is how can disable source js file or js file in main module in my own created module

Tthank you

**Comment by vovayatsyuk** [comment]
Sorry, but I need to see your sources to help.

**Comment by ppeyman** [comment]
> Sorry, but I need to see your sources to help.

Ok i uploaded here soon 
regard
