### ISSUE TITLE
htmlentities encodes non-latin chars

### ISSUE THREAD

**Issue by uvarovdev** [breezefront/module-breeze#35]
Hi. It seems breeze using htmlentities to encode html. But it's also affects non-latin chars. So the page source code becomes larger. Is it bug or why?

**Comment by vovayatsyuk** [comment]
Can you check if the fix works for you?

**Comment by McAlex220** [comment]
It seems so. Thanks.

/breeze/Model/**Filter.php**
**process** function
```
$document = new \DOMDocument();
$document->loadHTML( utf8_decode( $html ) );
//$document->loadHTML($html);
```
and

```
$html = $document->saveHTML($document->documentElement);
//$html = $document->saveHTML();
$html = $this->unescapeNestedHtmlTags($html);
$html = $this->unescapeHtmlEntities($html);
```

**Comment by vovayatsyuk** [comment]
Thanks. But I meant to check my commit - https://github.com/breezefront/module-breeze/commit/dd8747925e93bf0670f69d3242d8ba98d51fadb1

**Comment by uvarovdev** [comment]
> Member

Missed that). Yes, your commit working as well.
