### ISSUE TITLE
Magento 2.4.5p1 - Bundle Product Qty not taken into account its always 1

### ISSUE THREAD

**Issue by ZIPITRO** [breezefront/module-breeze#36]
We are using M2.4.5-p1
PHP 8.1

Expected result:
When adding 2 products from a bundle page, adding to cart to have the correct qty of the products.

Current result:
When adding 2 products from a bundle page, adding to cart gives qty=1 for each selected product.

Select bundle product
![bundle-1](https://user-images.githubusercontent.com/22952492/213160857-f426350d-5500-4ccf-829e-0981bf529cdb.png)

Adding 1 product with a quantity of 3
![bundle-2](https://user-images.githubusercontent.com/22952492/213160885-578339aa-b046-4e5e-ab6b-8903de02f994.png)

Quick view in cart gives only a quantity of 1
![bundle-3](https://user-images.githubusercontent.com/22952492/213161296-ae02e159-f647-484e-bb69-51c8e9dc6951.png)

With breeze disabled it works normal.

Please have a look.

Thank you!

**Comment by vovayatsyuk** [comment]
Can you reproduce it at our demo?

https://breeze.swissupdemo.com/breeze_evolution/sprite-yoga-companion-kit.html

**Comment by ZIPITRO** [comment]
Hi [vovayatsyuk](https://github.com/vovayatsyuk) !
Could not reproduce on the breeze evolution, I will check if with vanilla Luma the problem persists.

Have a great day!

**Comment by vovayatsyuk** [comment]
Do you use the latest breeze module and theme? ~2.3
