### ISSUE TITLE
write permission error with advanced js bundling

### ISSUE THREAD

**Issue by sandipansaha** [breezefront/module-breeze#40]
Hi Support,

With enabling the "Advanced JS Bundling" in the cloud we are seeing the below write permission error as the cloud is a read-only server.
We are using Breeze blank theme along with swissup page speed module.

            "name": "swissup/breeze-blank",
            "version": "2.3.3",

            "name": "swissup/module-breeze",
            "version": "2.4.5",

            "name": "swissup/module-pagespeed",
            "version": "1.7.0",

![image](https://user-images.githubusercontent.com/4614581/228611760-2e96bef5-b21d-4a28-a10e-fddbab8e3187.png)

[1b956cb810aa437362b7d8dcede2f44f40c67ba83e30fca40a4fb96d372c4d3b.log](https://github.com/breezefront/module-breeze/files/11103300/1b956cb810aa437362b7d8dcede2f44f40c67ba83e30fca40a4fb96d372c4d3b.log)

**Comment by vovayatsyuk** [comment]
1. There is no need to enable "Advanced Bundling" because it's useless for Breeze. Breezefront will bundle js sources by itself if "JS merging" or "JS bundling" is enabled (standard magento options).
2. I think you need to run `bin/magento setup:static-content:deploy` command from the terminal in read-only environments.

**Comment by sandipansaha** [comment]
Hi,
The issue is persisting even after disabling the "Advanced JS Bundling" with the latest Breeze module.
With a cloud environment, you can not run the static content deploy manually due to a read-only environment. The command is part of the auto-deployment process and runs in build mode.
Thanks

**Comment by sandipansaha** [comment]
I have disabled the "advanced js bundling" now, but I had enabled JS to merge. I guess that is triggering the on-fly js bundle by the breeze.
But with the cloud read-only structure, it is not possible. This should be part of the static content deploy process.
I am managing these settings through app/etc/config.php

**Comment by vovayatsyuk** [comment]
Can you tell me how would you enable default js bundling when you don't have Breeze or any other module?

**Comment by sandipansaha** [comment]
we add them into config.php
![image](https://user-images.githubusercontent.com/4614581/228768840-353b885b-0f2e-4c02-aa52-91e4d8bd9a0d.png)

**Comment by vovayatsyuk** [comment]
And then the cloud would automatically deploy static content? 

It should work the same way with Breeze. We have a [plugin](https://github.com/breezefront/module-breeze/blob/master/Plugin/Bundle.php#L65) that runs additional logic after default deployment is completed.

**Comment by vovayatsyuk** [comment]
> But it should handle the read-only scenarios with JS merge enabled or we are not able to use this with the cloud.

The plugin I've referenced is made for that.

Could you please debug if the deployment was actually done by the cloud and if our plugin was called?

**Comment by sandipansaha** [comment]
Yes, I am sure that static content is being generated as a part of cloud deployment.
![image](https://user-images.githubusercontent.com/4614581/228775776-cadead02-d56d-49f7-968c-9d7d128cee61.png)

I can share the cloud deployment log privately if required.

Also, please note that in the cloud we can set instructions in various deployment stages using the hook like this.
![image](https://user-images.githubusercontent.com/4614581/228777325-09d719f5-cc40-48a6-b279-89ef0ebefc2f.png)


Please read the following docs for more details -
https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/develop/deploy/process.html?lang=en
https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/develop/deploy/scenario-based.html?lang=en

I can try to debug by adding some log into the plugin if it is being executed. But that is probably running at the build stage. But I would suggest that you could read the cloud deployment process so you could understand it better than me.

Thanks

**Comment by vovayatsyuk** [comment]
> But that is probably running at the build stage

Yes, it should be running during deployment.

Thanks for the links. But before writing additional code I would like to find out why our plugin is not working. Maybe it failed due to some errors?

**Comment by sandipansaha** [comment]
Hi,

Could you please share your email ID so we can provide you access to our cloud sandbox account?

Thanks

**Comment by sandipansaha** [comment]
Hi,
I have not been able to copy your email address, please send me an email to sandipan.saha@williamscommerce.com
Thanks

**Comment by vovayatsyuk** [comment]
Thank you for the access, I was able to fix the issue - 2.5.0 is just tagged!

The main issue why it wasn't working correctly was the fact that breeze js bundles depend on config values. For example, when you enable ReCaptcha for some stores, Breeze will add the corresponding js component to the bundle.

This logic was working correctly only for global config values, not per website or per store levels. I've made a [few fixes](https://github.com/breezefront/module-breeze/compare/031d1fb50b7a4016df507a739fdcbd0d64d2f1b3...e8b24b8b46509fe4fdc79e36a65657d0560251b7) to read store configs correctly during deployment. 

Another tackle is the no-DB environment during deployment. Since we don't have access to the DB, Breeze requires you to [create a config.php dump](https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/develop/upgrade/commerce-version.html?lang=en#create-a-config.php-file).

p.s. Maybe in future releases I will add an ability to dump only those config options that Breeze wants to read, because `app:config:dump` commands dumps too much. What do you think, is it worth implementing?

**Comment by vovayatsyuk** [comment]
Added a guide about Magento Cloud zero-downtime deployments: https://breezefront.com/docs/cloud-commerce

**Comment by sandipansaha** [comment]
Ah, I understand now what you meant in the previous message.
The config:dump command dumps all the settings into the config.php and also disables the field in the admin. So, it is very much inconvenient for the developer and user as well.
So, I think it will a very good option to add an ability to dump only those config options that Breeze wants to read from the breeze_default layout.

Thanks

**Comment by sandipansaha** [comment]
Hi,
Still getting the error while I have enabled the JS Merged option. Could you please check?
![image](https://user-images.githubusercontent.com/4614581/230931966-636299ef-babf-43b7-ab7a-355cca88908f.png)

Thanks

**Comment by vovayatsyuk** [comment]
Your config.php is missing actual data. For example, google analytics is enabled for the website level, but config.php is missing that info.

Here is the part of old config.php:

```
...
'websites' => [
    'breeze' => [
        'google' => [
            'analytics' => [
                'active' => '1',
                ...
            ]
        ]
    ]
]
...
```

**Comment by vovayatsyuk** [comment]
Thanks! [Fixed](https://github.com/breezefront/module-breeze/commit/23ef4cb5e8bda5a58dccad1c7365c4476f32e6b8)

'container_id', 'measurement_id', and 'conversion_id' are removed in the latest Breeze: https://github.com/breezefront/module-breeze/commit/e8b24b8b46509fe4fdc79e36a65657d0560251b7
