### ISSUE TITLE
Install of swissup/module-rtl failed

### ISSUE THREAD

**Issue by Daniel-Zadora** [breezefront/module-breeze#43]
[Exception]
  Higher matching version 2.5.3 of swissup/module-breeze was found in public repository packagist.org
                               than 2.5.1 in private https://repo.magento.com. Public package might've been taken
   over by a malicious entity,
                               please investigate and update package requirement to match the version from the private repository

**Comment by dimdimich** [comment]
We just submited recent release to Magento marketplace. Please try to install it in next 15 minutes. We also suggest to install Breeze directly from our repository as ussualy there is delay between official release and module submission to Marketplace.
