### ISSUE TITLE
Magento default frontend form validation does not work with Breeze which works with Luma

### ISSUE THREAD

**Issue by sandipansaha** [breezefront/module-breeze#45]
Magento default frontend form validation does not work with Breeze which works with Luma.

Using the class name with arguments like "validate-clean-url" does not work.
As an example,
with the breeze:
![image](https://user-images.githubusercontent.com/4614581/234292219-0761e202-5a3c-4417-a461-149070ce45e2.png)

with no breeze (debug mode):
![image](https://user-images.githubusercontent.com/4614581/234291337-50c6339c-7d62-45db-86cd-cc02c8dc6d1d.png)

Even the "validate-email" does not work completely -
with the breeze:
![image](https://user-images.githubusercontent.com/4614581/234292403-56d25864-0dec-4118-8599-afa9db679520.png)

with no breeze (debug mode):
![image](https://user-images.githubusercontent.com/4614581/234291874-9d54b9b5-a617-4eec-a1d2-8c2db856dca7.png)

Only "required-entry" works as expected.

**Comment by vovayatsyuk** [comment]
Can you change your form to use data-validate attributes? Example: https://github.com/magento/magento2/blob/HEAD/app/code/Magento/Contact/view/frontend/templates/form.phtml#L47

p.s. It will not fix the 'validate-clean-url' because this validator is not implemented in Breeze. For now, I recommend using `input type="url"`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

**Comment by sandipansaha** [comment]
Hi @vovayatsyuk 

Tested. The validation does not work with the Breeze demo contact form as well.

URL:
![image](https://user-images.githubusercontent.com/4614581/234311905-9c2d0a66-03e9-4332-a048-bd29fe3fd625.png)

Email:
![image](https://user-images.githubusercontent.com/4614581/234311424-9b42a7ab-a3f1-4fb8-9cfb-1c1bad998a88.png)

Breeze demo contact form Email and Tel:
![image](https://user-images.githubusercontent.com/4614581/234310933-510fdc94-d23f-4f85-8152-c6fc3bc6c8b0.png)

**Comment by vovayatsyuk** [comment]
Magento has a lot of [built-in validators](https://github.com/magento/magento2/blob/HEAD/app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js#L60), but I don't think we need them in Breeze out of the box.

For now, I suggest you to add your own validator:

```js
$.validator.validators['validate-clean-url'] = [
    (value) => $.validator.utils.isEmptyNoTrim(value) || /^(http|https|ftp):\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+.(com|org|net|dk|at|us|tv|info|uk|co.uk|biz|se)$)(:(\d+))?\/?/i.test(value) || /^(www)((\.[A-Z0-9][A-Z0-9_-]*)+.(com|org|net|dk|at|us|tv|info|uk|co.uk|biz|se)$)(:(\d+))?\/?/i.test(value),
    $t('Please enter a valid URL. For example http://www.example.com or www.example.com.')
];
```

**Comment by vovayatsyuk** [comment]
Added docs about forms validation: https://breezefront.com/docs/validator
