### ISSUE TITLE
InstagramFeed Code is not compatible with breeze theme

### ISSUE THREAD

**Issue by Chandu9012** [breezefront/module-breeze#51]
I am using Mageplaza InstagramFeed extension and it is working fine on login page where login page excluded from breeze. I need Instagram Feed on homepage and category page but there are not working the nstagram feed because those pages are not excluded from breeze. I have installed breeze theme extension as well. 

I need to make below code compatible with breeze. Please help me.

<script type="text/x-magento-init">
    {
        "#mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?>": {
            "mageplaza/instagram": {
                "id": "<?= /** @noEscape */ $widgetId ?>",
                "url": "<?= /** @noEscape */ $block->getUrl('mp_instagram/feed/get') ?>",
                "count": "<?= /** @noEscape */ $total ?>",
                "layout": "<?= /** @noEscape */ $options['layout'] ?>",
                "items_slider":"<?= /** @noEscape */ $items_slider ?>",
                "show_caption": "<?= /** @noEscape */ $options['show_caption'] ?>",
                "show_popup": "<?= /** @noEscape */ $options['show_popup'] ?>",
                "show_video": "<?= /** @noEscape */ $options['show_video'] ?>"
            }
        }
    }
    </script>

**Comment by vovayatsyuk** [comment]
Please use [discussions](https://github.com/orgs/breezefront/discussions) instead of issues.
