### ISSUE TITLE
"RTL fixes" breaks CSS compilation as ".margin" is not declared

### ISSUE THREAD

**Issue by sky-hub** [breezefront/module-breeze#54]
https://github.com/breezefront/module-breeze/blame/1ada8caada6a70854cf8ff226e3f375635aedd9a/view/frontend/web/css/source/components/_gallery.less#L167

**Comment by vovayatsyuk** [comment]
`swissup/module-rtl` is [required](https://github.com/breezefront/module-breeze/blob/master/composer.json#L8)

If it's not enabled, enable it with the following command:

```
bin/magento module:enable Swissup_Rtl
```

**Comment by sky-hub** [comment]
Fair enough. Issue can be closed.
