### ISSUE TITLE
Disabling Turbo doesn't remove source files

### ISSUE THREAD

**Issue by nfourteen** [breezefront/module-breeze#58]
Using `swissup/module-breeze` v2.9.1, `swissup/theme-frontend-breeze-blank` v2.5.6, and Magento 2.4.6.

I have a complex set of UI components that have been implemented with AlpineJS v3.13.0 as I couldn't get them working using the `$.view` function. But I get the following error in the console and nothing works:

```
Uncaught RangeError: Maximum call stack size exceeded
    at alpine-3.8.1.js:311:75
    at Array.forEach (<anonymous>)
    at recurse (alpine-3.8.1.js:311:67)
    at alpine-3.8.1.js:319:25
    at Array.forEach (<anonymous>)
    at recurse (alpine-3.8.1.js:311:67)
    at alpine-3.8.1.js:319:25
    at Array.forEach (<anonymous>)
    at recurse (alpine-3.8.1.js:311:67)
    at alpine-3.8.1.js:319:25
```

I've tracked this down to Turbolinks. If I set "Enable Turbo Feature" to "No" in theme configuration, the Turbo sources are still loaded and the error persists.

Is there a way to remove the Turbolinks source files if the feature is disabled? Or is there a way to make it play nicely with AlpineJS? I'm using the `Alpine.store()` global and the issue seems to be stemming from there. But I have yet to find a work around other than commenting out `vendor/swissup/module-breeze/view/frontend/layout/breeze_default.xml:40` and `vendor/swissup/module-breeze/view/frontend/layout/breeze_default.xml:65`.

**Comment by vovayatsyuk** [comment]
Added check for `enabled` flag. 

But I would like to fix compatibility with AlpineJS as well. Could you please post the minimal example to reproduce the issue?

**Comment by nfourteen** [comment]
@vovayatsyuk Thank you! And yes, I will hopefully get you a module that reproduces the issues shortly. In creating a simple counter component using `Alpine.store()`, I can't reproduce. So it seems it's not what I thought it was and maybe not related to Breeze at all🤞. 

I will let you know either way what I find. Should have some time this weekend to work on reproducing.

**Comment by nfourteen** [comment]
@vovayatsyuk This was indeed a mistake on my part. In one of the KO components, I needed a reference to the `window` object to get screen size and stored a reference in a local property. In converting that component to an AlpineJs component, I missed removing the local property. This caused the `initInterceptors2()` AlpineJs method to iterate over the entire window object 😬 , eventually hanging on recursing over the Turbolinks history delegate.

I've got this fixed and everything seems to be compatible with AplineJs in Breeze. We can close this issue, but I do like that you've updated to not include the resources when Turbo is not enabled. I'll leave this open for your tracking of that PR.

Thanks for all the work you've done on Breeze!

**Comment by vovayatsyuk** [comment]
Oh, I see. That was tricky. Thanks for letting me know :+1:
