### ISSUE TITLE
Override or extend minicart JS

### ISSUE THREAD

**Issue by dellg5** [breezefront/module-breeze#61]
Hello, 

I'd like to add my own add to cart via a popup slide on the right. Is it possible to do this? 

I overloaded the necessary files on Magento to do this but it failed. I saw that you had rewritten minicart.js in the component folder as well as the phtml and ko templates.

Do I need to overload the whole thing? to add functions?
I don't understand the logic

![image](https://github.com/breezefront/module-breeze/assets/60648111/91660d41-3086-43f6-8192-95692ebcef4a)
![image](https://github.com/breezefront/module-breeze/assets/60648111/31417014-d7eb-4e5b-9ffa-383d9210741f)

Do I need to integrate my functions into your minicart file and modify it to make it work?

**Comment by vovayatsyuk** [comment]
I'm not sure I understand what are you doing. Do you have the modal already? Do you want to render minicart in this modal?

p.s. You can apply styles to existing minicart so it will look like slidepanel:

```
.minicart-wrapper .mage-dropdown-dialog {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    margin: 0;
    border-radius: 0;
}
```

<img width="775" height="441" src="https://github.com/breezefront/module-breeze/assets/306080/00ccff37-90f4-410f-98a7-e9917a86d4d0"/>

**Comment by dellg5** [comment]
Thank you for taking the time to read and answer my questions.

I couldn't display any modal except the basic one from minicart.js line 270 => self.initSidebar();
when you click on icon, on('dropdownDialog:open) execute.
That's not what I want to do and I don't understand how to do it in your minicart.js file...

If possible, I'd like to display a slide modal with the contents of the shopping cart inside, along with all the necessary information, as shown in this example.
![image](https://github.com/breezefront/module-breeze/assets/60648111/92bc1b1f-00a1-4c1b-9d7b-b591247b5dc5)
![image](https://github.com/breezefront/module-breeze/assets/60648111/1161cf7c-45b7-4c1b-bfca-912682b21751)

**Comment by vovayatsyuk** [comment]
I still don't understand why not show existing minicart dropdown without creating new components.

Js to open the minicart:

```js
$('[data-block="minicart"]').find('[data-role="dropdownDialog"]').dropdownDialog('open');
```

Example on how to automatically show the minicart after cart was updated:

```js
var cartSubscriber;

$(document).on('breeze:load', () => {
    cartSubscriber = $.sections.get('cart').subscribe(() => {
        $('[data-block="minicart"]').find('[data-role="dropdownDialog"]').dropdownDialog('open');
    });
});

$(document).on('breeze:destroy', () => {
    cartSubscriber.dispose();
});
```

CSS to make it look like slideout:

```css
& when not (@critical) {
  .minicart-wrapper .mage-dropdown-dialog {
    position: fixed;
    top: 0 !important;
    right: 0;
    bottom: 0;
    margin: 0;
    border-radius: 0;
  }
}
```
