### ISSUE TITLE
Modal popup wrong class

### ISSUE THREAD

**Issue by CptCharlesG** [breezefront/module-breeze#62]
Hello,

It looks like something is wrong with modal popup class naming.

I faced this issue in two cases:

1.
When guest checkout is disabled, the authentication popup modal gets "**modal-popuppopup-authentication** _show" class missing a space between popu**pp**opup. Therefore the the whole modal fails to function.

![image](https://github.com/breezefront/module-breeze/assets/9698214/593ca1f6-4a66-48f9-9c47-44fd4ad5116d)

Steps to reproduce:
- Enable Breeze js (2.11.1)
- Disable guest checkout
- Add something to the cart
- Click on the "Proceed to Checkout" link on the cart page or in the minicart
- Modal will be added to the end of the page in the background

2.
Same issue when trying to remove product from minicart and the confirmation popup appears.

I tried it with the latest Argento Breeze themes, Breeze Base theme.
Also I enabled Breeze js for the Luma based that otherwise works well but fails the same way when Breeze js enabled.
Also I tried Argento Breeze Stripes with Breeeze js off (by ?breeze=0) and then it works.
Strangely it works on the demo sites - are they up to date?

Unfortunately I could not find the origin of the problem.
(It works after adding the space manually in the browser)

Thank you for your help!

**Comment by CptCharlesG** [comment]
It is a HTML (?) minify issue I think. 

Spaces have been removed inside <aside>:
`<script type="text/html" id="popupTpl" data-breeze><!----><aside role="dialog"class="modal-<%- data.type %><%- data.modalClass %>`

I have disabled Swissup_Pagespeed, but no luck yet.

It still have spaces inside:
Swissup\Breeze\Block\KoTemplate.php
Swissup\Breeze\Block\HtmlTemplate.php

**Comment by CptCharlesG** [comment]
It was caused a 3rd party HTML minify module (from old theme supplier)
Closing the issue, sorry for posting...

**Comment by vovayatsyuk** [comment]
Thanks for letting us know what was the reason for the issue.
