### ISSUE TITLE
Incompatibility with Magento 2.4.6-p6 (latest security patch)

### ISSUE THREAD

**Issue by pabodah** [breezefront/module-breeze#67]
Hello,

Seems like there is an incompatibility with the latest Magento version 2.4.6-p6

Before the upgrade

- In checkout > shipping, “Ship here” button is working and Shipping methods can be checked

After the upgrade 

- In checkout > shipping, “Ship here” button is NOT working and Shipping methods cannot be checked

[339077672-7a2a6cda-d0dc-4e98-9019-d1bbcf694ec4.webm](https://github.com/breezefront/module-breeze/assets/1543867/ccea1407-e1f4-468b-8502-e69f46c75ccf)

**Comment by vovayatsyuk** [comment]
I cannot reproduce it on 2.4.7. Please provide the link to your site so I can see what is wrong.

**Comment by pabodah** [comment]
I'm testing this in local so I don't have a link yet to provide. 

I'm using the following versions
![Screenshot from 2024-06-13 13-54-17](https://github.com/breezefront/module-breeze/assets/1543867/983730df-a4e7-42c4-80d2-faed5dd892bf)

**Comment by vovayatsyuk** [comment]
Can you inspect these elements using developer toolbar and see why they do not appear on hover?

**Comment by vovayatsyuk** [comment]
Hello, @pabodah! Have you resolved this issue?

**Comment by pabodah** [comment]
Hello,

This was resolved using `<csp>
            <policies>
                <storefront_checkout_index_index>
                    <scripts>
                        <inline>1</inline>
                    </scripts>
                </storefront_checkout_index_index>
            </policies>
        </csp>`
