### ISSUE TITLE
Error whit component.js - this.hasTemplate is not a function

### ISSUE THREAD

**Issue by rafaelnc** [breezefront/module-breeze#69]
After updating to the latest version I get this error:

![issue breeze](https://github.com/breezefront/module-breeze/assets/19422095/4f3309d5-136d-4f63-8781-1c176f4d8eca)
app/code/Swissup/Breeze/view/frontend/web/js/core/component.js : 461

**Comment by vovayatsyuk** [comment]
It looks like you are on the master branch. The master branch isn't stable and is under development. Use the stable release instead.

**Comment by vovayatsyuk** [comment]
https://github.com/breezefront/module-breeze/commit/099320156eada6038f78fc78d4c4a8d51f317442
