### ISSUE TITLE
Issue with html filter

### ISSUE THREAD

**Issue by ArniXXX** [breezefront/module-breeze#70]
Hello guys. 

Faced the issue with your module, 

More details you can see here https://stackoverflow.com/questions/33426788/domdocument-removing-closing-tag-within-script-tags

Solution is

File: vendor/swissup/module-breeze/Model/Filter.php

Line 50: 
`$document->loadHTML($html);`

Change with 
`$document->loadHTML($html, LIBXML_HTML_NODEFDTD | LIBXML_SCHEMA_CREATE);`

**Comment by vovayatsyuk** [comment]
Can you please add steps to reproduce the issue?

I've just tried to add

```js
<script>
    console.log("<h1>hello</h1>");
</script>
```

to the `swissup/module-breeze/view/frontend/templates/theme/js/require_js.phtml` and everything works as expected.

**Comment by vovayatsyuk** [comment]
It's working fine in breeze without the proposed solution because we escape all tags inside the script and style tags: https://github.com/breezefront/module-breeze/blob/master/Model/Filter.php#L98-L133

However, if the proposed solution covers the same cases with `script` and `style` we can remove these `escape/unescape` functions :+1:

**Comment by thanych1** [comment]
In my case, all this is reproduced very simply. The site just doesn't work normally.

<img width="1248" alt="image" src="https://github.com/user-attachments/assets/e56ff7e2-96f3-4dff-83e6-37203831feb5">

-

**Comment by vovayatsyuk** [comment]
I was hoping for HTML content that I need to insert somewhere to reproduce the error.

**Comment by thanych1** [comment]
Your theme collects templates for knockout js here. It is these templates that break

<img width="1886" alt="image" src="https://github.com/user-attachments/assets/8948d8c7-9c71-4628-8881-37ef3ee1d8a5">
